name: cd-pipeline
on:
  - push
  - workflow_dispatch

jobs:
  cd-pipeline:
    needs: ci-pipeline
    environment: github-pages
    permissions:
      pages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4