name: ci-workflow
on:
  - push
  - workflow_dispatch

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: ./.github/actions/install
      - run: npm run prettier
      - run: npm run typecheck
      - run: npm run test
      - run: npm run build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist/
  cd-pipeline:
    needs: ci-pipeline
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - id: deploy-pages
        uses: actions/deploy-pages@v4
      - run: echo "${{ steps.deploy-pages.outputs.page_url }}"
      - id: page_url
        run: echo "page_url=${{ steps.deploy-pages.outputs.page_url }}" >> "$GITHUB_OUTPUT"
    outputs:
      page-url: ${{ steps.deploy-pages.outputs.page_url }}
  smoke-test:
    needs: cd-pipeline
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        browser: [ firefox, chromium ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/install
      - name: Install Playwright Browsers
        run:
          npx playwright install ${{ matrix.browser }}
      - name: Run Playwright tests
        run: |
          echo $PLAYWRIGHT_BASE_DOMAIN
          npx playwright test --project ${{ matrix.browser }}
        env:
          PLAYWRIGHT_BASE_DOMAIN: ${{ needs.cd-pipeline.outputs.page-url }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name:
            playwright-report-${{ matrix.browser }}

          path: playwright-report/

          retention-days: 1
